# Generated by Django 4.2.6 on 2023-10-29 01:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.CharField(max_length=5)),
                ('Jurisdiction', models.CharField(max_length=100)),
                ('Charges', models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=1000), django.core.validators.MinValueValidator(limit_value=1)])),
                ('Days_of_disposal', models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=1000), django.core.validators.MinValueValidator(limit_value=1)])),
                ('City', models.CharField(max_length=100)),
                ('Years_of_Experience', models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=100), django.core.validators.MinValueValidator(limit_value=0)])),
                ('Type_of_Lawyer', models.CharField(max_length=100)),
                ('Languages', models.CharField(max_length=100)),
                ('Pro_bono', models.CharField(max_length=5)),
                ('Lawyer_Name', models.CharField(max_length=100)),
                ('Lawfirms', models.CharField(max_length=100)),
                ('Demography', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
            ],
        ),
    ]
